name: Deploy to Snowflake with schemachange

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install schemachange snowflake-connector-python

      - name: Create connections.toml
        run: |
          echo "[connections.snowflake]" > connections.toml
          echo "account = \"aia76005.east-us-2.azure\"" >> connections.toml
          echo "user = \"DUMAR\"" >> connections.toml
          echo "password = \"dfVTkMMXXskFH8w\"" >> connections.toml
          echo "role = \"ACCOUNTADMIN\"" >> connections.toml
          echo "warehouse = \"COMPUTE_WH\"" >> connections.toml
          echo "database = \"SNOWFLAKE_SANDBOX_DB\"" >> connections.toml
          echo "schema = \"PUBLIC\"" >> connections.toml
          echo "=== connections.toml content ==="
          cat connections.toml

      - name: Test Snowflake connection
        run: |
          python - <<'EOF'
import snowflake.connector
conn = snowflake.connector.connect(
    user='DUMAR',
    password='dfVTkMMXXskFH8w',
    account='aia76005.east-us-2.azure',
    warehouse='COMPUTE_WH',
    database='SNOWFLAKE_SANDBOX_DB',
    schema='PUBLIC'
)
print('✅ Conexión exitosa!')
conn.close()
EOF

      - name: Check migrations folder
        run: |
          echo "=== Listing migrations folder ==="
          ls -la migrations || echo "⚠️ 'migrations' folder not found"

      - name: Run schemachange
        run: |
          schemachange deploy --connections-file-path connections.toml -f migrations --create-change-history-table
