name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.8.x'

      - name: Install schemachange
        run: |
          pip install schemachange

      - name: Create connections.toml
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
        run: |
          echo "[connections.snowflake]" > connections.toml
          echo "account = \"$SF_ACCOUNT\"" >> connections.toml
          echo "user = \"$SF_USERNAME\"" >> connections.toml
          echo "password = \"$SF_PASSWORD\"" >> connections.toml
          echo "role = \"$SF_ROLE\"" >> connections.toml
          echo "warehouse = \"$SF_WAREHOUSE\"" >> connections.toml
          echo "database = \"$SF_DATABASE\"" >> connections.toml
          echo "schema = \"$SF_SCHEMA\"" >> connections.toml
          echo "=== connections.toml content ==="
          cat connections.toml

      - name: Run schemachange
        env:
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 2: Running schemachange"
          # Se usa el nombre de la tabla de historial: database.schema.table (3 partes)
          schemachange deploy --connections-file-path connections.toml -f $GITHUB_WORKSPACE/migrations -c $SF_DATABASE.$SF_SCHEMA.CHANGE_HISTORY --create-change-history-table
