name: Deploy Schema Changes to Snowflake

on:
  push:
    branches:
      - main  # O la rama que uses para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange

      - name: Debug Secret Lengths
        run: |
          echo "Verificando longitud de los secretos..."
          echo "SF_ACCOUNT length: ${#${{ secrets.SF_ACCOUNT }}}"
          echo "SF_USERNAME length: ${#${{ secrets.SF_USERNAME }}}"
          echo "SF_PASSWORD length: ${#${{ secrets.SF_PASSWORD }}}"
          echo "SF_ROLE length: ${#${{ secrets.SF_ROLE }}}"
          echo "SF_WAREHOUSE length: ${#${{ secrets.SF_WAREHOUSE }}}"
          echo "SF_DATABASE length: ${#${{ secrets.SF_DATABASE }}}"
          echo "SF_SCHEMA length: ${#${{ secrets.SF_SCHEMA }}}"

      - name: Create connections.toml with Secrets
        run: |
          echo "Creando connections.toml..."
          cat << EOF > connections.toml
          [connections.snowflake]
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USERNAME }}"
          password = "${{ secrets.SF_PASSWORD }}"
          role = "${{ secrets.SF_ROLE }}"
          warehouse = "${{ secrets.SF_WAREHOUSE }}"
          database = "${{ secrets.SF_DATABASE }}"
          schema = "${{ secrets.SF_SCHEMA }}"
          EOF

      - name: Run schemachange
        run: schemachange -f migrations -c connections.toml --create-change-history-table
